### ISSUE TITLE
infografia- TypeScript

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-ka194#1]
[Infografía-LUZ KARINA-  TypeScript.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-ka194/files/15204765/Infografia-LUZ.KARINA-.TypeScript.pdf)

**Comment by josealfredo79** [comment]
calificacion..???

**Comment by josealfredo79** [comment]
Necesito avanzar y no hay calificación...

**Comment by josealfredo79** [comment]
Calificación 18
